### ISSUE TITLE
Неточности при расставлении аспектов

### ISSUE THREAD

**Issue by AsianMoscow** [SergTyapkin/thaumcraft-auto-researcher#9]
![image](https://github.com/user-attachments/assets/e1e2605e-8a12-49ba-85c1-dde9e08f4111)

В данном примере не расставлен аспект Vacous, это очень часто происходит.

![image](https://github.com/user-attachments/assets/ce14b48f-5984-4bc3-9c6e-722dabca4ecd)

1. Вместо Vitreus стоит Vitium
2. Вместо Victus промахнулся и взял аспект на ячейку выше Venenum

И последнее, в авто режиме иногда "теряет" бумажку с исследованием и просто водит курсором по столу без неё.

Если это пофиксить, то 90% исследований сделает автоматом.
UPD. Скрины починил. 
UPD2. И ещё в некоторых местах вместо ордо ставит 
![image](https://github.com/user-attachments/assets/b8860cca-8ee8-4599-93f4-1e109859e69a)
Tincturem

**Comment by SergTyapkin** [comment]
Добрый день!
Спасибо за обращение. Но у вас не работают ссылки на скриншоты.
 
Гитхаб умеет загружать скриншоты сам по их обычной вставке (ctrl+v) при изменении текста. Попробуйте так, пожалуйста

**Comment by AsianMoscow** [comment]
> Добрый день! Спасибо за обращение. Но у вас не работают ссылки на скриншоты.
> 
> Гитхаб умеет загружать скриншоты сам по их обычной вставке (ctrl+v) при изменении текста. Попробуйте так, пожалуйста

Я обновил верхний пост ...

**Comment by AsianMoscow** [comment]
Если бы можно было делать скрин когда он предложил решение и когда уже решил было бы проще искать ошибки. В большинстве случаев ему нехватает парочки действий чтобы полностью доделать. А так скрипт очень классный, я хотел сделать подобное, но к сожалению нехватило скилла...

**Comment by SergTyapkin** [comment]
Скорее всего у вас не хватает одного аспекта, который должен быть где-то в центре (в списке всех аспектов). Потому на тех аспектах, что стоят ближе к концу, происходит смещение на 1 вверх. 

В этом файле можно узнать, какие аддоны добавляют какие аспекты:
https://github.com/SergTyapkin/thaumcraft-auto-researcher/blob/master/aspects_configs/addonsAspectsRecipes.json

Посмотрите внимательно и найдёте, какого не хватает. Его нужно изучить, и все встанет на свои места

**Comment by AsianMoscow** [comment]
> Скорее всего у вас не хватает одного аспекта, который должен быть где-то в центре (в списке всех аспектов). Потому на тех аспектах, что стоят ближе к концу, происходит смещение на 1 вверх.
> 
> В этом файле можно узнать, какие аддоны добавляют какие аспекты: https://github.com/SergTyapkin/thaumcraft-auto-researcher/blob/master/aspects_configs/addonsAspectsRecipes.json
> 
> Посмотрите внимательно и найдёте, какого не хватает. Его нужно изучить, и все встанет на свои места

у меня получается так, если я вручную расставлю "виктус", "вакус" и "кристалис" он идеально отрабатывает

**Comment by SergTyapkin** [comment]
Скорее всего у вас не хватает одного аспекта, который должен быть где-то в центре (в списке всех аспектов). Потому на тех аспектах, что стоят ближе к концу, происходит смещение на 1 вверх. 

В этом файле можно узнать, какие аддоны добавляют какие аспекты:
https://github.com/SergTyapkin/thaumcraft-auto-researcher/blob/master/aspects_configs/addonsAspectsRecipes.json

Посмотрите внимательно, и найдёте, какого не хватает. Его нужно изучить и все встанет на свои места

**Comment by SergTyapkin** [comment]
Отправьте, пожалуйста, список аддонов и версию игры
 (или вместо этого всего отправьте все .log файлы из папки C://users/*Пользователь*/.ThaumcraftAutoResearcher).

Так же понадобятся скриншоты всех открытых вами аспектов в столе исследований (несколько скриншотов (около 3-ех), чтобы на них уместились все аспекты). 

Обычно программа не даёт таких сбоев. Это поможет разобраться

**Comment by AsianMoscow** [comment]
Thaumcraft-1.7.10-4.2.3.5
Avaritia-1.13
ForbiddenMagic-1.7.10-0.575

![image](https://github.com/user-attachments/assets/c349ee50-522d-443e-a19a-b93fe8d91438)
![image](https://github.com/user-attachments/assets/d41eef8c-676c-4145-83e5-6795f43bd155)
![image](https://github.com/user-attachments/assets/83deab91-3626-42d1-8d92-d2c76b7ec44c)

неточности в основном тут:
![image](https://github.com/user-attachments/assets/036a184f-1b8e-4056-9b0b-a059f089d9a5)
я показал что ставит вместо чего. я уже всё исследовал с помощью вашей программы,
эти аспекты я расставлял вручную сразу, чтобы скрипт не поместил ненужный.
Вот логи из папки "C:\Users\asian\.ThaumcraftAutoResearcher\logs"
[logs.zip](https://github.com/user-attachments/files/17576706/logs.zip)
